project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path: '..'
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true

files:
  [
    {
      source: 'src/Themes/default/languages/Optimus/Optimus.english.php',
      dest: 'Themes/default/languages/Optimus/Optimus.english.php',
      translation: '%original_path%/Optimus.%language%.php',
    },
  ]
